name: Npm Build

on: [pull_request, push]

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Npm Install
        run: npm install

      - name: Run Build
        run: npm run build
